### ISSUE TITLE
ValueError: '$1' is not in list

### ISSUE THREAD

**Issue by ashishpatel26** [zhuango/KAN#1]
**I was getting error about test dataset which is not available in data forlder.** and this extra error doesn't make a sense. would you please help me with this.

```bash
!python3 main.py --trainPath ../data/train.txt --validPath ../data/valid.txt --testPath ../data/testGoldHomo.txt --trainGold ../data/trainGold.txt --testPath ../data/testGold.txt --batchSize 100 --wd 100 --ed 100 --hop 2 --clas 2 --epoch 20 --wePath ../data/wordEmb/bio-word2id100 --w2IDPath ../data/wordEmb/bio-embed100 --eePath ../data/KB/entity2vec.vec --rePath ../data/KB/relation2vec.vec --t2idPath ../data/KB/triple2id.txt --e2idPath ../data/KB/entity2id.txt --paraPath ./parameters/kan --results ./results/ --training True --lr 0.1 --wdecay 0.0 --validsetR 0.15
```

```python
True
Loading word id...
Loading word vectors...
Loading entity vectors...
Loading relation vectors...
Loading triples...
Loading entity id mapping...
Load test samples...
Traceback (most recent call last):
  File "main.py", line 333, in <module>
    sampleTuple = GetInstanceProperty(sample)
  File "main.py", line 196, in GetInstanceProperty
    e1Index = words.index("$1")
ValueError: '$1' is not in list
```

**Comment by zhuango** [comment]
@ashishpatel26 Hi Ashish, it's been a long time since i work on this project. Hope the following info is usefull. The $1 means a placeholder for an entity in a context, which is done in the data preprocessing phrase. So it seems that your dataset does not follow the preprocessing steps mentioned in the paper, please find the preprocessing code in ‘preprocessing’ folder.
As for the dataset, you can check it at [Biocreative website ](https://biocreative.bioinformatics.udel.edu/tasks/biocreative-vi/track-4/).
Further, I found a mistake in the command line and updated it: '--testPath ../data/testGold.txt' -> '--testGold ../data/testGold.txt', please have a check on that.
